apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Изменяем количество реплик для dev

# Или проще - используем patchesStrategicMerge
# patchesStrategicMerge:
#   - patch_deployment.yaml

# Добавляем окружение в название
namePrefix: dev-

# Добавляем общие лейблы
commonLabels:
  environment: dev
