apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxxxxxapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xxxxxxapp
  template:
    metadata:
      labels:
        app: xxxxxxapp
    spec:
      containers:
      - name: xxxxxxapp
        image: nginx:latest
        ports:
        - containerPort: 80
